/**
 *
 * @copyright &copy; 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * We kindly request you to use one or more of the following phrases to refer to
 * foxBMS in your hardware, software, documentation or advertising materials:
 *
 * - "This product uses parts of foxBMS&reg;"
 * - "This product includes parts of foxBMS&reg;"
 * - "This product is derived from foxBMS&reg;"
 *
 */

/**
 * @file    test_flash_cfg.c
 * @author  foxBMS Team
 * @date    2024-09-17 (date of creation)
 * @updated 2026-04-20 (date of last update)
 * @version v1.11.0
 * @ingroup UNIT_TEST_IMPLEMENTATION
 * @prefix  TEST
 *
 * @brief   Test of some module
 * @details TODO
 */

/*========== Includes =======================================================*/
#include "unity.h"

#include "flash_cfg.h"

/*========== Unit Testing Framework Directives ==============================*/
TEST_SOURCE_FILE("flash_cfg.c")

TEST_INCLUDE_PATH("../../src/bootloader/driver/config")
/* The upstream ":files: :test:" exclusion in
 * conf/unit/bootloader_project_posix.yml that removes this file is CORRECT and
 * is left in place. Unlike the two test_fstartup.c files, this one is not
 * unblocked by removing a path.
 *
 * WHAT IS ACTUALLY MISSING
 * ------------------------
 * flash_cfg.h:62 does `#include "F021.h"`. F021.h is TI's proprietary F021
 * Flash API header, shipped in the separately licensed "F021 Flash API
 * 02.01.01" package that this line names and that the project's own build
 * scripts also reference by absolute Windows path
 * (src/bootloader/wscript:42-45 explains that _L2FMC must be defined before
 * F021.h is included and cites the F021 Flash API 02.01.01 Reference Guide,
 * SPNU501G at line 45; the linker flag in
 * src/bootloader/main/bootloader.cmd:215 names
 * F021_API_CortexR4_BE_L2FMC_V3D16.lib in the same tree; the test's sibling
 * wscripts resolve C:/ti/Hercules/F021 Flash API/02.01.01/include). It is not
 * generated by HALCoGen - it is not in conf/hcg/bootloader.hcg - and it is not
 * redistributable source in this repository.
 *
 * Verified absent, on this tree, at the time of writing:
 *   - no file named F021*.h anywhere in the repository (case-sensitive search
 *     across the whole tree excluding .git);
 *   - no F021 header in the SIL host harness interface directory
 *     (docs/artifacts/.work/verification-env/sil/iface/, which supplies
 *     HL_*.h stand-ins for the TI HAL but nothing for the flash API);
 *   - no F021 header in either SIL build tree.
 * The only near-match anywhere is HL_errata_SSWF021_45.h, which is a HALCoGen
 * errata header about the same silicon family and has nothing to do with the
 * flash API.
 *
 * WHY NO F021.h IS SUPPLIED HERE
 * ------------------------------
 * Compiling flash_cfg.c needs the real API's types, not merely a shape. The
 * module uses the flash-bank enumerators Fapi_FlashBank0 (18 occurrences),
 * Fapi_FlashBank1 (17) and Fapi_FlashBank7 (33) - 68 in
 * src/bootloader/driver/config/flash_cfg.c - plus Fapi_FlashBankType (2, in
 * flash_cfg.h), and the sector tables are keyed on those enumerators together
 * with base and end addresses. The sibling flash driver, which is compiled from
 * the same header, additionally needs Fapi_StatusType, Fapi_Status_Success,
 * Fapi_Status_FsmReady, Fapi_AutoEccGeneration and the Fapi_* entry points
 * (Fapi_initializeFlashBanks, Fapi_setActiveFlashBank,
 * Fapi_enableMainBankSectors, Fapi_enableEepromBankSectors, Fapi_EraseSector,
 * Fapi_issueProgrammingCommand, Fapi_issueAsyncCommandWithAddress,
 * Fapi_serviceWatchdogTimer).
 *
 * Those enumerators encode which bank and which sector ranges the L2FMC
 * controller of this device exposes. Writing stand-ins for them here would mean
 * inventing a flash-bank and sector geometry - fabricating exactly the device
 * description this test is about - and the result would compile and could be
 * made to pass while asserting nothing about the real geometry. A host stand-in
 * that merely compiles is worse than an honest exclusion, so no F021.h is
 * created.
 *
 * STATE OF THE TEST BODY, so the exclusion is not mistaken for coverage
 * ---------------------------------------------------------------------
 * Measured, not assumed: this file currently contains exactly one test,
 * void testBOOT_NothingToTest(void), whose body is the single call
 * BOOT_NothingToTest(); (this file, the Test Cases section). It registers no
 * expectations, and with comments stripped it contains zero assertion macros -
 * counted mechanically, not by eye. So even on a host that HAS the F021
 * Flash API installed, this test would report one passing case and assert
 * nothing about the flash geometry. That is a gap in the test, not something
 * this exclusion causes and not something this change can close: fixing it means
 * writing new test cases against the real Fapi_* types, which needs the real
 * F021.h. It is recorded here rather than left for a reader to discover.
 */
TEST_INCLUDE_PATH("C:/ti/Hercules/F021 Flash API/02.01.01/include")

/*========== Definitions and Implementations for Unit Test ==================*/

/*========== Setup and Teardown =============================================*/
void setUp(void) {
}

void tearDown(void) {
}

/*========== Test Cases =====================================================*/

void testBOOT_NothingToTest(void) {
    BOOT_NothingToTest();
}
