#!/usr/bin/env python3
"""Emit the clock-frequency constants the SIL interface needs, READ FROM THE
repository's own committed HALCoGen configuration input.

WHY THIS IS NOT FABRICATION
---------------------------
`conf/hcg/app.dil` is shipped in the repository and is HALCoGen's *input*. It
holds 11,971 configuration keys, among them the clock-tree frequencies in MHz.
The harness reads the value it needs from that file and writes it into a
generated header. Nothing is typed by hand and nothing is guessed: the mapping
from the .dil key to the TI macro name is fixed below and each generated line
carries the .dil key it came from, so a reader can check it.

This is exactly the technique the pre-existing verification-env runbook already
uses for `HALCOGEN_CPU_CLOCK_HZ`
(DRIVER.OS.VAR.OS_CPUCLOCKHZ.VALUE in the same file).

WHAT IS STILL NOT AVAILABLE
---------------------------
The .dil holds the *configuration* frequencies. It does NOT hold:
  * the byte offset or bit position of any register,
  * the base address of any peripheral,
  * the value of a device-identity field such as DEVID/DIEID,
  * the internal structure of any TI driver function.
Those remain unmodelled and are listed in sil/REPORT.md.

Usage: gen_clock_constants.py <app.dil> <output-header>
"""

from __future__ import annotations

import pathlib
import re
import sys

# SIL macro name -> the .dil key that supplies its value, and the unit conversion
# the repository's own source applies to it. Every entry was read off a
# foxBMS source line; the line is quoted so it can be re-checked.
#
#   macro            .dil key                                        repo source
MAP = {
    # src/app/driver/mcu/mcu.c: (RTI_FREQ) * 1000000.0f
    "RTI_FREQ": (
        "DRIVER.SYSTEM.VAR.CLKT_RTI1_FREQ",
        "MHz, used as `(RTI_FREQ) * 1000000.0f`",
        "src/app/driver/mcu/mcu.c:57  mcu_frcClock_Hz = (uint32_t)((RTI_FREQ) * 1000000.0f) / ((MCU_RTI_CNT0_CPUC0_REG) + 1u);",
    ),
    "HCLK_FREQ": (
        "DRIVER.SYSTEM.VAR.CLKT_HCLK_FREQ",
        "MHz",
        "named by src/app/driver/uart/uart.c and the FreeRTOS port",
    ),
    "VCLK_FREQ": (
        "DRIVER.SYSTEM.VAR.CLKT_VCLK1_FREQ",
        "MHz",
        "named by the repository's clock configuration",
    ),
    "AVCLK1_FREQ": (
        "DRIVER.SYSTEM.VAR.CLKT_AVCLK1_FREQ",
        "MHz",
        "named by src/app/driver/afe/ltc/ltc_*.c",
    ),
    "CPU_FREQ": (
        "DRIVER.SYSTEM.VAR.CLKT_GCLK_FREQ",
        "MHz",
        "named by the repository's clock configuration",
    ),
    "PLL1_FREQ": (
        "DRIVER.SYSTEM.VAR.CLKT_PLL1_FREQ",
        "MHz",
        "named by the repository's clock configuration",
    ),
    "PLL2_FREQ": (
        "DRIVER.SYSTEM.VAR.CLKT_PLL2_FREQ",
        "MHz",
        "named by the repository's clock configuration",
    ),
    "OSCILLATOR_FREQ": (
        "DRIVER.SYSTEM.VAR.CLKT_OSCILLATOR_FREQ",
        "MHz",
        "named by the repository's clock configuration",
    ),
    "EXTERNAL_FREQ_INPUT": (
        "DRIVER.SYSTEM.VAR.CLKT_EXTERNAL_FREQ_INPUT",
        "MHz",
        "named by the repository's clock configuration",
    ),
}


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    dil = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[2])
    text = dil.read_text(encoding="utf-8", errors="replace")

    values: dict[str, str] = {}
    for key in {v[0] for v in MAP.values()}:
        m = re.search(rf"^\s*{re.escape(key)}\.VALUE=(\S+)\s*$", text, re.MULTILINE)
        if not m:
            print(f"ERROR: {key} not found in {dil}", file=sys.stderr)
            return 1
        values[key] = m.group(1)

    lines = [
        "/* ==========================================================================",
        " *  SIL HOST-DECLARED CONSTANTS  --  GENERATED, DO NOT EDIT",
        " * ==========================================================================",
        " *",
        " *  GENERATED BY sil/tools/gen_clock_constants.py from",
        f" *      {dil.name}  (HALCoGen INPUT, committed in this repository)",
        " *",
        " *  Every value below is READ OUT of that file. None is typed by hand and",
        " *  none is a reconstruction of a TI register map. The .dil holds the",
        " *  clock-tree configuration; it does not hold register offsets, base",
        " *  addresses or bit positions, and none of those are claimed here.",
        " *",
        " *  Each line names the exact .dil key it came from so a reader can verify",
        " *  it. Values are in MHz, as the .dil expresses them.",
        " *",
        " *  IMPORTANT SCOPE LIMIT: these constants are read by the host build only",
        " *  so that drivers which do clock arithmetic compile and can be asserted",
        " *  on. They describe the project's own clock configuration. They are NOT",
        " *  a timing model: the harness executes no time, models no latency, and",
        " *  no statement about real-time behaviour follows from any test here.",
        " * =========================================================================",
        " */",
        "#ifndef FOXBMS_SIL_HOST_GENERATED_CLOCK_CONSTANTS_H_",
        "#define FOXBMS_SIL_HOST_GENERATED_CLOCK_CONSTANTS_H_",
        "",
    ]
    for macro, (key, unit, source) in MAP.items():
        lines.append(f"/* from {key}.VALUE = {values[key]} ({unit}) */")
        lines.append(f"/*   {source} */")
        lines.append(f"#ifndef {macro}")
        lines.append(f"#define {macro} ({int(float(values[key]))})")
        lines.append(f"#endif /* {macro} */")
        lines.append("")
    lines.append("#endif /* FOXBMS_SIL_HOST_GENERATED_CLOCK_CONSTANTS_H_ */")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    for macro, (key, _, _) in MAP.items():
        print(f"  {macro:<22} <- {key}.VALUE = {values[key]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
