/* ==========================================================================
 *  SIL HOST-DECLARED CONSTANTS  --  GENERATED, DO NOT EDIT
 * ==========================================================================
 *
 *  GENERATED BY sil/tools/gen_clock_constants.py from
 *      app.dil  (HALCoGen INPUT, committed in this repository)
 *
 *  Every value below is READ OUT of that file. None is typed by hand and
 *  none is a reconstruction of a TI register map. The .dil holds the
 *  clock-tree configuration; it does not hold register offsets, base
 *  addresses or bit positions, and none of those are claimed here.
 *
 *  Each line names the exact .dil key it came from so a reader can verify
 *  it. Values are in MHz, as the .dil expresses them.
 *
 *  IMPORTANT SCOPE LIMIT: these constants are read by the host build only
 *  so that drivers which do clock arithmetic compile and can be asserted
 *  on. They describe the project's own clock configuration. They are NOT
 *  a timing model: the harness executes no time, models no latency, and
 *  no statement about real-time behaviour follows from any test here.
 * =========================================================================
 */
#ifndef FOXBMS_SIL_HOST_GENERATED_CLOCK_CONSTANTS_H_
#define FOXBMS_SIL_HOST_GENERATED_CLOCK_CONSTANTS_H_

/* from DRIVER.SYSTEM.VAR.CLKT_RTI1_FREQ.VALUE = 100.000 (MHz, used as `(RTI_FREQ) * 1000000.0f`) */
/*   src/app/driver/mcu/mcu.c:57  mcu_frcClock_Hz = (uint32_t)((RTI_FREQ) * 1000000.0f) / ((MCU_RTI_CNT0_CPUC0_REG) + 1u); */
#ifndef RTI_FREQ
#define RTI_FREQ (100)
#endif /* RTI_FREQ */

/* from DRIVER.SYSTEM.VAR.CLKT_HCLK_FREQ.VALUE = 100.000 (MHz) */
/*   named by src/app/driver/uart/uart.c and the FreeRTOS port */
#ifndef HCLK_FREQ
#define HCLK_FREQ (100)
#endif /* HCLK_FREQ */

/* from DRIVER.SYSTEM.VAR.CLKT_VCLK1_FREQ.VALUE = 100.000 (MHz) */
/*   named by the repository's clock configuration */
#ifndef VCLK_FREQ
#define VCLK_FREQ (100)
#endif /* VCLK_FREQ */

/* from DRIVER.SYSTEM.VAR.CLKT_AVCLK1_FREQ.VALUE = 100.000 (MHz) */
/*   named by src/app/driver/afe/ltc/ltc_*.c */
#ifndef AVCLK1_FREQ
#define AVCLK1_FREQ (100)
#endif /* AVCLK1_FREQ */

/* from DRIVER.SYSTEM.VAR.CLKT_GCLK_FREQ.VALUE = 300.000 (MHz) */
/*   named by the repository's clock configuration */
#ifndef CPU_FREQ
#define CPU_FREQ (300)
#endif /* CPU_FREQ */

/* from DRIVER.SYSTEM.VAR.CLKT_PLL1_FREQ.VALUE = 300.00 (MHz) */
/*   named by the repository's clock configuration */
#ifndef PLL1_FREQ
#define PLL1_FREQ (300)
#endif /* PLL1_FREQ */

/* from DRIVER.SYSTEM.VAR.CLKT_PLL2_FREQ.VALUE = 80.00 (MHz) */
/*   named by the repository's clock configuration */
#ifndef PLL2_FREQ
#define PLL2_FREQ (80)
#endif /* PLL2_FREQ */

/* from DRIVER.SYSTEM.VAR.CLKT_OSCILLATOR_FREQ.VALUE = 20.0 (MHz) */
/*   named by the repository's clock configuration */
#ifndef OSCILLATOR_FREQ
#define OSCILLATOR_FREQ (20)
#endif /* OSCILLATOR_FREQ */

/* from DRIVER.SYSTEM.VAR.CLKT_EXTERNAL_FREQ_INPUT.VALUE = 25.0 (MHz) */
/*   named by the repository's clock configuration */
#ifndef EXTERNAL_FREQ_INPUT
#define EXTERNAL_FREQ_INPUT (25)
#endif /* EXTERNAL_FREQ_INPUT */

#endif /* FOXBMS_SIL_HOST_GENERATED_CLOCK_CONSTANTS_H_ */
